name: flutter_brotli
description: Flutter Brotli
version: 0.0.2
homepage: https://github.com/linkkader/flutter_brotli/blob/main/example/lib/dart_brotli_example.dart
repository: https://github.com/linkkader/flutter_brotli

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  ffi: ^2.0.1

  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  ffigen: ^7.2.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  plugin:
    platforms:
      android:
        package: com.linkkader.flutter_brotli.flutter_brotli
        pluginClass: FlutterBrotliPlugin
      ios:
        pluginClass: FlutterBrotliPlugin
      linux:
        pluginClass: FlutterBrotliPlugin
      macos:
        pluginClass: FlutterBrotliPlugin
      windows:
        pluginClass: FlutterBrotliPluginCApi

ffigen:
  output: 'lib/generated_bindings.dart'
  name: 'CBrotli'
  comments: false

  headers:
    entry-points:
      - 'br/include/brotli/brotli.h'
